blank_issues_enabled: false

contact_links:
  - name: Ask a question
    url: https://github.com/jmeridth/first-time-contributor-workshop/discussions/new
    about: Ask a question or start a discussion
